server:
  port: 80

spring:
  application:
    name: springcloud-consumer-dept
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0

#Eureka配置
eureka:
  client:
    register-with-eureka: false   #不向eureka注册自己
    service-url:
      defaultZone:  http://localhost:7001/eureka/


